//! `scl-repo` — the durable on-disk repository: `.sc/` layout, refs/HEAD,
//! named branches, a git-like working tree, and commit/secret orchestration.

pub mod diff3;
pub(crate) mod conflicts;
pub mod scanner;
pub mod textdiff;
pub mod scanner_patterns;
pub mod error;
pub mod gc;
pub mod http_transport;
pub mod ignore;
pub mod git_marks;
pub mod layout;
pub mod lock;
pub mod merge;
pub mod merge_state;
pub mod oplog;
pub mod pick_state;
pub mod promisor;
pub mod protect;
pub mod protect_ops;
pub mod reachable;
pub mod rebase_state;
pub mod refs;
pub mod remote;
pub mod replay;
pub mod repo;
pub mod rewrap;
pub mod secrets;
pub mod serve_tokens;
pub mod signatures;
pub mod sparse;
pub mod stdio_transport;
pub mod sync;
pub mod transport;
pub mod wire;
pub(crate) mod ws;
pub mod workspace;
pub mod worktree;

pub use conflicts::{ActiveOp, ConflictKind, ConflictVersions, ResolveSide, Side};
pub use error::{Error, Result};
pub use gc::GcStats;
pub use git_marks::MarksStore;
pub use http_transport::ScHttpUrl;
pub use oplog::{OpRecord, UndoOutcome};
pub use promisor::Promisor;
pub use protect_ops::PrefixRecipient;
pub use remote::{RemoteConfig, RemoteKind};
pub use replay::{PickResult, RebaseResult};
pub use repo::{Repo, Status};
pub use rewrap::RewrapReport;
pub use scanner::ScanReport;
pub use secrets::SecretInfo;
pub use signatures::SigStatus;
pub use sparse::Sparse;
pub use stdio_transport::{open_transport, SshUrl, StdioTransport};
pub use workspace::{HarvestResult, WorkOptions, WorkspaceOutcome};
pub use worktree::Diff;
pub use ws::{WsEntry, WsHarvestOutcome, WsSession};
